name: CI/CD

on:
  push:
    branches: [ master, homolog ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ format(github.ref != 'refs/heads/master' && 'homolog' || 'production') }}
    steps:
      - uses: actions/checkout@v2
        
      - name: Run a generic echo
        run: echo Hello, world!

      - name: Run a dynamic echo
        run: |
          echo ${{ secrets.message }}
